// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-focused-input.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var get_focused_input_default = defineTool({
  name: "get_focused_input",
  title: "Get session focus",
  description: "Return the currently focused SRT input for a MAKO session, showing which stream operators are watching in 1-up mode.",
  inputSchema: {
    session_id: z.string().min(1).describe("The MAKO session ID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ session_id }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("session_focus").select("session_id, focused_input_id, focused_by, updated_at").eq("session_id", session_id).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: `No focus set for session ${session_id}.` }] };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { focus: data }
    };
  }
});

// src/lib/mcp/tools/list-feedback.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_feedback_default = defineTool2({
  name: "list_recent_feedback",
  title: "List recent feedback",
  description: "Return the most recent user-submitted feedback entries for the MAKO app (newest first).",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).default(10).describe("Max entries to return (1-50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("feedback").select("id, first_name, last_name, email, message, page_url, created_at").order("created_at", { ascending: false }).limit(limit);
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { feedback: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/submit-feedback.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.95.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
var submit_feedback_default = defineTool3({
  name: "submit_feedback",
  title: "Submit feedback",
  description: "Submit a feedback entry to the MAKO app on behalf of a user.",
  inputSchema: {
    first_name: z3.string().trim().min(1).max(80),
    last_name: z3.string().trim().min(1).max(80),
    email: z3.string().email(),
    message: z3.string().trim().min(1).max(4e3),
    page_url: z3.string().url().optional().describe("Optional page URL the feedback relates to.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ first_name, last_name, email, message, page_url }) => {
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("feedback").insert({ first_name, last_name, email, message, page_url: page_url ?? null }).select().single();
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: `Feedback submitted (id ${data.id}).` }],
      structuredContent: { feedback: data }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "mako-mcp",
  title: "MAKO Broadcast MCP",
  version: "0.1.0",
  instructions: "Tools for the MAKO live-broadcast platform. Read session focus state, browse recent user feedback, and submit new feedback entries on a user's behalf.",
  tools: [get_focused_input_default, list_feedback_default, submit_feedback_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
